# All values are given in SI units (e.g. m, s, rad)

initial_state:
  x: 0.0
  y: 0.0
  theta: 1.5708

input_limits:
  steering_angle_min: -0.5
  steering_angle_max: 0.5
  linear_velocity_min: -5
  linear_velocity_max: 5

fixed_linear_velocity: 1.0

vehicle_dimensions:
  wheelbase: 1.0

simulation_options:
  dt: 0.1

spline_planner:
  interpolation_distance: 0.1

pure_pursuit:
  lookahead_distance: 1.0
